#!/usr/bin/env bash
# Clean up devcontainer containers/images for a given host suffix (e.g., host123)
# without touching shared base images. Usage:
#   HOST_SUFFIX=host123 [DOCKER_CONTEXT=...] [DRY_RUN=1] ./scripts/cleanup_devcontainers.sh
set -euo pipefail

HOST_SUFFIX="${HOST_SUFFIX:-}"
DRY_RUN="${DRY_RUN:-0}"
DOCKER_CONTEXT="${DOCKER_CONTEXT:-}"

if [[ -z "$HOST_SUFFIX" ]]; then
  echo "ERROR: set HOST_SUFFIX (e.g., host123) to match config/env/devcontainer.<host>.*.env" >&2
  exit 1
fi

DOCKER_CMD=(docker)
if [[ -n "$DOCKER_CONTEXT" ]]; then
  DOCKER_CMD=(docker --context "$DOCKER_CONTEXT")
fi

echo "[clean] Host suffix       : $HOST_SUFFIX"
echo "[clean] Docker context    : ${DOCKER_CONTEXT:-default}"
echo "[clean] Dry run           : ${DRY_RUN}"

# Collect container names to remove (both running and stopped)
mapfile -t containers < <("${DOCKER_CMD[@]}" ps -a --format '{{.Names}}' | grep -Ei "vsc-.*_${HOST_SUFFIX}_" || true)

# Collect devcontainer images to remove from env files
declare -A images_map=()
for envf in config/env/devcontainer."${HOST_SUFFIX}".*.env; do
  [[ -f "$envf" ]] || continue
  # shellcheck disable=SC1090
  source "$envf"
  if [[ -n "${DEVCONTAINER_IMAGE:-}" ]]; then
    images_map["$DEVCONTAINER_IMAGE"]=1
  fi
done

# Add feature images generated by devcontainer CLI for this host suffix
mapfile -t feature_images < <("${DOCKER_CMD[@]}" images --format '{{.Repository}}:{{.Tag}}' | grep -Ei "vsc-.*_${HOST_SUFFIX}_" || true)
for img in "${feature_images[@]}"; do
  images_map["$img"]=1
done

images=("${!images_map[@]}")

echo "[clean] Containers to remove (${#containers[@]}): ${containers[*]:-<none>}"
echo "[clean] Images to remove (${#images[@]}): ${images[*]:-<none>}"

if [[ "$DRY_RUN" == "1" ]]; then
  echo "[clean] Dry-run enabled; no removals performed."
  exit 0
fi

if ((${#containers[@]})); then
  "${DOCKER_CMD[@]}" rm -f "${containers[@]}"
fi

if ((${#images[@]})); then
  "${DOCKER_CMD[@]}" rmi -f "${images[@]}"
fi

echo "[clean] Done."
