#!/usr/bin/env bash
set -euo pipefail

# Generates a dedicated SSH config for the cpp devcontainer using values from
# config/env/devcontainer.env (or an override). This keeps ProxyJump/tunnel
# settings out of ~/.ssh/config while giving a simple alias for tools/CLIs.
#
# Usage:
#   ./scripts/generate_cpp_devcontainer_ssh_config.sh [--env-file path] [--output path] [--proxy-user user]
#
# Defaults:
#   env-file:   <repo>/config/env/devcontainer.env
#   output:     ~/.ssh/cpp-devcontainer.conf

usage() {
  cat <<'USAGE'
Usage: scripts/generate_cpp_devcontainer_ssh_config.sh [options]

Options:
  --env-file <path>   Path to devcontainer env file (default: config/env/devcontainer.env)
  --output  <path>    Output SSH config path (default: ~/.ssh/cpp-devcontainer.conf)
  --proxy-user <user> Override ProxyJump user (default: DEVCONTAINER_REMOTE_USER; omit to use local default)
  -h, --help          Show this help
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/config/env/devcontainer.env"
OUTPUT_PATH="${HOME}/.ssh/cpp-devcontainer.conf"
PROXY_USER=""
PROXY_USER_SET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --output) OUTPUT_PATH="$2"; shift 2 ;;
    --proxy-user) PROXY_USER="$2"; PROXY_USER_SET=1; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

[[ -f "$ENV_FILE" ]] || { echo "Env file not found: $ENV_FILE" >&2; exit 1; }

# Load env values; keep only what we need.
# shellcheck disable=SC1090
source "$ENV_FILE"

REMOTE_HOST="${DEVCONTAINER_REMOTE_HOST:-}"
REMOTE_USER="${DEVCONTAINER_REMOTE_USER:-}"
REMOTE_PORT="${DEVCONTAINER_SSH_PORT:-9222}"
if [[ "$PROXY_USER_SET" -eq 0 ]]; then
  PROXY_USER="${DEVCONTAINER_PROXY_USER:-${DEVCONTAINER_REMOTE_USER:-}}"
fi

[[ -n "$REMOTE_HOST" ]] || { echo "DEVCONTAINER_REMOTE_HOST is missing in $ENV_FILE" >&2; exit 1; }
[[ -n "$REMOTE_USER" ]] || { echo "DEVCONTAINER_REMOTE_USER is missing in $ENV_FILE" >&2; exit 1; }

# Resolve the host via ssh -G to capture search domains/canonical name if available.
RESOLVED_PROXY_HOST="$REMOTE_HOST"
if command -v ssh >/dev/null 2>&1; then
  CANON="$(ssh -G "$REMOTE_HOST" 2>/dev/null | awk '/^hostname /{print $2}' | head -n1 || true)"
  if [[ -n "$CANON" ]]; then
    RESOLVED_PROXY_HOST="$CANON"
  fi
fi

mktmp_proxy_jump() {
  if [[ -z "$PROXY_USER" ]]; then
    echo "${RESOLVED_PROXY_HOST}"
  else
    echo "${PROXY_USER}@${RESOLVED_PROXY_HOST}"
  fi
}

PROXY_JUMP_VALUE="$(mktmp_proxy_jump)"

mkdir -p "${HOME}/.ssh"
cat > "$OUTPUT_PATH" <<EOF
# Auto-generated by scripts/generate_cpp_devcontainer_ssh_config.sh
# Host values from: $ENV_FILE
Include ~/.ssh/config
Host cpp-devcontainer
    HostName 127.0.0.1
    Port ${REMOTE_PORT}
    User ${REMOTE_USER}
    ProxyJump ${PROXY_JUMP_VALUE}
    IdentitiesOnly yes
    ForwardAgent yes
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF

chmod 600 "$OUTPUT_PATH"
echo "Wrote SSH config to $OUTPUT_PATH"
echo "Connect with: ssh -F \"$OUTPUT_PATH\" cpp-devcontainer"
